name: rocket-league-api
version: 0.0.0

dependencies:
  - aeson
  - base
  - containers
  - http-client-tls
  - scientific
  - servant
  - servant-client
  - servant-docs
  - text
  - vector
ghc-options: -Wall

executables:
  rocket-league-api:
    main: rocket-league-api.hs
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
